# Generated by Django 5.2.5 on 2025-08-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passoword_hash',
            new_name='password_hash',
        ),
    ]
